---
title: "DMProject"
author: "Xin Xu"
date: "April 20, 2018"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is our project:

```{r message=TRUE, warning=TRUE, include=FALSE}
library(caTools)
library(survey)
library(readr)
library(dplyr)
library(party)
library(rpart)
library(rpart.plot)
library(ROCR)
library(pROC)
#preprocessing of data
SpotifyData=read.csv("data.csv", header = TRUE)
SpotifyData$duration_ms=(SpotifyData$duration_ms-min(SpotifyData$duration_ms))/(max(SpotifyData$duration_ms)-min(SpotifyData$duration_ms))
SpotifyData$loudness=(SpotifyData$loudness-min(SpotifyData$loudness))/(max(SpotifyData$loudness)-min(SpotifyData$loudness))
SpotifyData$tempo=(SpotifyData$tempo-min(SpotifyData$tempo))/(max(SpotifyData$tempo)-min(SpotifyData$tempo))
SpotifyData$key=as.factor(SpotifyData$key)
SpotifyData$time_signature=as.factor(SpotifyData$time_signature)
SpotifyData$mode=as.factor(SpotifyData$mode)
#training and test set seperation
split = sample.split(SpotifyData$target, SplitRatio = 0.7)
SpotifyData.Train = SpotifyData[split, ]
SpotifyData.Test = SpotifyData[!split, ]
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
#Logistic regression
glm.target=glm(target ~ acousticness + danceability + duration_ms + energy + instrumentalness + key + liveness + loudness + mode + speechiness + tempo + time_signature + valence, data=SpotifyData.Train, family = "binomial")
summary(glm.target)
glm.target=glm(target ~ acousticness + danceability + duration_ms + instrumentalness + loudness + speechiness, data=SpotifyData.Train, family = "binomial")
summary(glm.target)
SpotifyPredictTest_LR = predict(glm.target, newdata = SpotifyData.Test, type = "response")
threshold = 0.4
LogReg=table(SpotifyData.Test$target, as.numeric(SpotifyPredictTest_LR >= threshold))

#Decision Tree
rtree_fit <- rpart(target ~ acousticness + danceability + duration_ms + energy + instrumentalness + key + liveness + loudness + mode + speechiness + tempo + time_signature + valence, data=SpotifyData.Train, method = "class", 
                   control = rpart.control(minbucket = 0.05*length(SpotifyData.Train$target)))
rpart.plot(rtree_fit)
SpotifyPredictTest <- predict(rtree_fit, newdata = SpotifyData.Test, type = "prob")
table(SpotifyData.Test$target, as.numeric(SpotifyPredictTest[,2] >= threshold))
#compare
ROC_curve_LR=roc(target~SpotifyPredictTest_LR, data=SpotifyData.Test)
plot(ROC_curve_LR, col="red")
par(new=TRUE)
plot(roc(SpotifyData.Test$target, SpotifyPredictTest[,2]))
```


